In [1]:
import faker
import pandas as pd

In [2]:
dir(faker.Faker())

['__annotations__',
 '__class__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_factories',
 '_factory_map',
 '_locales',
 '_map_provider_method',
 '_select_factory',
 '_select_factory_choice',
 '_select_factory_distribution',
 '_unique_proxy',
 '_weights',
 'aba',
 'add_provider',
 'address',
 'administrative_unit',
 'am_pm',
 'android_platform_token',
 'ascii_company_email',
 'ascii_email',
 'ascii_free_email',
 'ascii_safe_email',
 'bank_country',
 'bban',
 'binary',
 'boolean',
 'bothify',
 'bs',
 'building_number',
 'cache_pattern',
 'catch_phrase',
 'century',
 'chrome',
 'city',
 'city_prefix',
 'city_suffix',
 'color',
 'color_name',
 'company',
 'company_email',
 'company_suffix',
 'coordinate',
 'country',
 'country_calling_code',
 'country_code',
 'credit_card_expire',
 'credit_card_full',
 'credit_card_number',
 'credit_card_provider',
 'credit_card_security_code',
 'cryptocurrency',
 'cryptocurrency_code',
 'cryptocurrency_name',
 'csv',
 'currency',
 'currency_code',
 'currency_name',
 'currency_symbol',
 'current_country',
 'current_country_code',
 'date',
 'date_between',
 'date_between_dates',
 'date_object',
 'date_of_birth',
 'date_this_century',
 'date_this_decade',
 'date_this_month',
 'date_this_year',
 'date_time',
 'date_time_ad',
 'date_time_between',
 'date_time_between_dates',
 'date_time_this_century',
 'date_time_this_decade',
 'date_time_this_month',
 'date_time_this_year',
 'day_of_month',
 'day_of_week',
 'del_arguments',
 'dga',
 'domain_name',
 'domain_word',
 'dsv',
 'ean',
 'ean13',
 'ean8',
 'ein',
 'email',
 'factories',
 'file_extension',
 'file_name',
 'file_path',
 'filter_by_length',
 'firefox',
 'first_name',
 'first_name_as_list',
 'first_name_female',
 'first_name_female_as_list',
 'first_name_male',
 'first_name_male_as_list',
 'first_name_nonbinary',
 'first_name_nonbinary_as_list',
 'fixed_width',
 'format',
 'free_email',
 'free_email_domain',
 'future_date',
 'future_datetime',
 'generator_attrs',
 'get_arguments',
 'get_formatter',
 'get_providers',
 'hex_color',
 'hexify',
 'hostname',
 'http_method',
 'iana_id',
 'iban',
 'image',
 'image_url',
 'internet_explorer',
 'invalid_ssn',
 'ios_platform_token',
 'ipv4',
 'ipv4_network_class',
 'ipv4_private',
 'ipv4_public',
 'ipv6',
 'isbn10',
 'isbn13',
 'iso8601',
 'items',
 'itin',
 'job',
 'json',
 'language_code',
 'language_name',
 'last_name',
 'last_name_as_list',
 'last_name_female',
 'last_name_female_as_list',
 'last_name_male',
 'last_name_male_as_list',
 'last_name_nonbinary',
 'last_name_nonbinary_as_list',
 'latitude',
 'latlng',
 'lexify',
 'license_plate',
 'linux_platform_token',
 'linux_processor',
 'local_latlng',
 'locale',
 'locales',
 'localized_ean',
 'localized_ean13',
 'localized_ean8',
 'location_on_land',
 'longitude',
 'mac_address',
 'mac_platform_token',
 'mac_processor',
 'md5',
 'military_apo',
 'military_dpo',
 'military_ship',
 'military_state',
 'mime_type',
 'month',
 'month_name',
 'msisdn',
 'name',
 'name_female',
 'name_male',
 'name_nonbinary',
 'nic_handle',
 'nic_handles',
 'null_boolean',
 'numerify',
 'opera',
 'paragraph',
 'paragraphs',
 'parse',
 'password',
 'past_date',
 'past_datetime',
 'phone_number',
 'port_number',
 'postalcode',
 'postalcode_in_state',
 'postalcode_plus4',
 'postcode',
 'postcode_in_state',
 'prefix',
 'prefix_as_list',
 'prefix_female',
 'prefix_female_as_list',
 'prefix_male',
 'prefix_male_as_list',
 'prefix_nonbinary',
 'prefix_nonbinary_as_list',
 'pricetag',
 'profile',
 'provider',
 'providers',
 'psv',
 'pybool',
 'pydecimal',
 'pydict',
 'pyfloat',
 'pyint',
 'pyiterable',
 'pylist',
 'pyset',
 'pystr',
 'pystr_format',
 'pystruct',
 'pytimezone',
 'pytuple',
 'random',
 'random_choices',
 'random_digit',
 'random_digit_not_null',
 'random_digit_not_null_or_empty',
 'random_digit_or_empty',
 'random_element',
 'random_elements',
 'random_int',
 'random_letter',
 'random_letters',
 'random_lowercase_letter',
 'random_number',
 'random_sample',
 'random_uppercase_letter',
 'randomize_nb_elements',
 'rgb_color',
 'rgb_css_color',
 'ripe_id',
 'safari',
 'safe_color_name',
 'safe_domain_name',
 'safe_email',
 'safe_hex_color',
 'secondary_address',
 'seed',
 'seed_instance',
 'seed_locale',
 'sentence',
 'sentences',
 'set_arguments',
 'set_formatter',
 'sha1',
 'sha256',
 'simple_profile',
 'slug',
 'ssn',
 'state',
 'state_abbr',
 'street_address',
 'street_name',
 'street_suffix',
 'suffix',
 'suffix_as_list',
 'suffix_female',
 'suffix_female_as_list',
 'suffix_male',
 'suffix_male_as_list',
 'suffix_nonbinary',
 'suffix_nonbinary_as_list',
 'swift',
 'swift11',
 'swift8',
 'tar',
 'text',
 'texts',
 'time',
 'time_delta',
 'time_object',
 'time_series',
 'timezone',
 'tld',
 'tsv',
 'unique',
 'unix_device',
 'unix_partition',
 'unix_time',
 'upc_a',
 'upc_e',
 'uri',
 'uri_extension',
 'uri_page',
 'uri_path',
 'url',
 'user_agent',
 'user_name',
 'uuid4',
 'weights',
 'windows_platform_token',
 'word',
 'words',
 'year',
 'zip',
 'zipcode',
 'zipcode_in_state',
 'zipcode_plus4']

In [72]:
first_name, last_name, email, phone_number, street_name, id, url, state, job = [], [], [], [], [], [], [], [], []
f = faker.Faker()
for i in range(100):
    first_name.append(f.first_name())
    last_name.append(f.last_name())
    email.append(f.email())
    phone_number.append(f.phone_number())
    street_name.append(f.street_name())
    id.append(f.uuid4())
    url.append(f.url())
    state.append(f.state())
    job.append(f.job())
    
import random
for i in range(100):
    jam = random.choice([ id, url, state, job])
    we = random.randint(0, 99)
    jam[we] = None

In [132]:
first_dictionary = {
    'id':id,
    'first_name':first_name,
    'last_name':last_name,
    'email':email,
    'phone_number':phone_number,
    'street_name':street_name
}
second_dictionary = {
    'id':id,
    'first_name':first_name,
    'last_name':last_name,
    'website_url':url,
    'state':state,
    'job':job
}

In [133]:
df1 = pd.DataFrame(first_dictionary)
df2 = pd.DataFrame(second_dictionary)

print(df1.shape, df2.shape)

(100, 6) (100, 6)

In [134]:
# df1.drop_duplicates(['first_name', 'last_name', 'email'], inplace=True)
print(df1.isna().sum())

id              24
first_name       0
last_name        0
email            0
phone_number     0
street_name      0
dtype: int64

In [135]:
df3 = df1.merge(df2)
df3

,id,first_name,last_name,email,phone_number,street_name,website_url,state,job
0,b55dce21-5ed6-460e-bf4e-60b53770676e,Wendy,Martinez,heatheralexander@example.com,622.294.9175x95374,Brandi Estate,http://www.campbell.com/,South Dakota,Insurance underwriter
1,5401f0d8-7aec-4acd-a660-9234cbcbd218,Christopher,Cook,batesmegan@example.org,(100)882-2608x722,Henderson Stream,https://hall.com/,North Carolina,None
2,5ad0f49c-ba8e-41cf-bf87-39db7db2a017,Justin,Cunningham,rwilliams@example.net,001-082-923-4311x85435,Jenkins Squares,http://pierce-underwood.info/,New Hampshire,None
3,97e6284a-6db2-49da-8ec4-7b12da40c46a,Robert,Ray,saraberry@example.org,(292)016-5529x15322,Baxter Center,https://perez.info/,None,Actor
4,None,Tiffany,Beasley,dwright@example.com,930.651.1459x46774,Melissa Flat,None,New Hampshire,Systems analyst
...,...,...,...,...,...,...,...,...,...
95,None,James,Fischer,hoodangela@example.net,+1-558-983-1057,Victor Expressway,None,Virginia,"Engineer, technical sales"
96,e85220e4-7460-4e21-a830-6a753daccaf1,Maria,Butler,dorseypeter@example.com,001-767-480-1589x570,Joanna Ramp,https://davis.net/,New Mexico,Human resources officer
97,f87d1418-c7b2-4d16-a4c2-c99598311b84,Maria,Cortez,jeremycrawford@example.com,358-140-1887,Campbell Stravenue,http://www.kelly.net/,None,Music tutor
98,2fa419bf-4754-453a-89e8-e6be0b015483,Jason,Cook,vsanchez@example.com,001-174-323-2673x64856,Kristina Gardens,https://www.lopez-anderson.com/,Idaho,Publishing copy
99,None,Randall,Martinez,zwright@example.net,(943)756-3783x041,Avery Parkway,https://www.reynolds-decker.com/,New Hampshire,Phytotherapist

In [136]:
df2.isna().any()

id              True
first_name     False
last_name      False
website_url     True
state           True
job             True
dtype: bool

In [137]:
df3 = pd.merge(df1, df2, on="id")

In [138]:
df3.shape

(652, 11)

In [139]:
df3.describe()

,id,first_name_x,last_name_x,email,phone_number,street_name,first_name_y,last_name_y,website_url,state,job
count,76,652,652,652,652,652,652,652,512,540,519
unique,76,79,81,100,100,100,79,81,74,40,79
top,b55dce21-5ed6-460e-bf4e-60b53770676e,James,Martinez,fwagner@example.net,001-420-079-8633x545,Wright Meadows,James,Martinez,https://www.murphy-osborne.com/,New Hampshire,Visual merchandiser
freq,1,27,26,24,24,24,27,26,24,50,25

In [140]:
df4 = df1.merge(df2, how="left")

In [141]:
df4

,id,first_name,last_name,email,phone_number,street_name,website_url,state,job
0,b55dce21-5ed6-460e-bf4e-60b53770676e,Wendy,Martinez,heatheralexander@example.com,622.294.9175x95374,Brandi Estate,http://www.campbell.com/,South Dakota,Insurance underwriter
1,5401f0d8-7aec-4acd-a660-9234cbcbd218,Christopher,Cook,batesmegan@example.org,(100)882-2608x722,Henderson Stream,https://hall.com/,North Carolina,None
2,5ad0f49c-ba8e-41cf-bf87-39db7db2a017,Justin,Cunningham,rwilliams@example.net,001-082-923-4311x85435,Jenkins Squares,http://pierce-underwood.info/,New Hampshire,None
3,97e6284a-6db2-49da-8ec4-7b12da40c46a,Robert,Ray,saraberry@example.org,(292)016-5529x15322,Baxter Center,https://perez.info/,None,Actor
4,None,Tiffany,Beasley,dwright@example.com,930.651.1459x46774,Melissa Flat,None,New Hampshire,Systems analyst
...,...,...,...,...,...,...,...,...,...
95,None,James,Fischer,hoodangela@example.net,+1-558-983-1057,Victor Expressway,None,Virginia,"Engineer, technical sales"
96,e85220e4-7460-4e21-a830-6a753daccaf1,Maria,Butler,dorseypeter@example.com,001-767-480-1589x570,Joanna Ramp,https://davis.net/,New Mexico,Human resources officer
97,f87d1418-c7b2-4d16-a4c2-c99598311b84,Maria,Cortez,jeremycrawford@example.com,358-140-1887,Campbell Stravenue,http://www.kelly.net/,None,Music tutor
98,2fa419bf-4754-453a-89e8-e6be0b015483,Jason,Cook,vsanchez@example.com,001-174-323-2673x64856,Kristina Gardens,https://www.lopez-anderson.com/,Idaho,Publishing copy
99,None,Randall,Martinez,zwright@example.net,(943)756-3783x041,Avery Parkway,https://www.reynolds-decker.com/,New Hampshire,Phytotherapist

In [144]:
df5 = df1.merge(df2, how='inner', on=['id', 'first_name', 'last_name'])

In [153]:
df10 = df5.dropna()

In [154]:
df10.drop_duplicates()

,id,first_name,last_name,email,phone_number,street_name,website_url,state,job
0,b55dce21-5ed6-460e-bf4e-60b53770676e,Wendy,Martinez,heatheralexander@example.com,622.294.9175x95374,Brandi Estate,http://www.campbell.com/,South Dakota,Insurance underwriter
7,60abc20b-603c-48c2-96ac-9c9a3bfa573e,Lisa,Perez,ericlane@example.org,537-541-8330x55136,Lang Coves,https://www.anderson.biz/,South Dakota,"Social research officer, government"
11,48355335-ee25-4c73-9f45-6a0e3a9d749b,Margaret,Wade,brianoconnell@example.net,+1-325-360-9263x1233,Heather Estates,http://www.cherry.biz/,Hawaii,"Scientist, research (life sciences)"
16,8132f36c-17ae-4e64-a59b-f873d7de4607,Stacey,House,matthewthomas@example.org,448-096-7006x95739,Thomas Brooks,https://chang-flynn.com/,Michigan,Tree surgeon
17,3e25a140-6273-4520-85a2-bb82f6c1afbe,Carla,Kramer,kelsey21@example.com,9154694548,Holloway Stravenue,http://esparza.biz/,Georgia,Visual merchandiser
20,53d8f111-c18c-4059-8959-e22352554361,Amy,Barron,curtisreyes@example.org,3696981740,Green Stream,https://www.peterson-parrish.com/,Oregon,Personnel officer
22,10a29e55-936a-4cb0-928f-2ce1e264d074,Nichole,Smith,alejandro77@example.net,001-727-883-3104x5248,Autumn Row,https://perkins.com/,Connecticut,"Editor, magazine features"
24,da82cac4-357c-45c6-b67f-735007371564,Jason,Hinton,patrick03@example.com,+1-394-252-5882x023,Gregory Ridge,https://www.jones.biz/,Connecticut,Systems developer
26,11bb83a5-64b4-482f-8bef-415017cf81a8,Matthew,Johnson,qevans@example.org,324.991.1656,Riley Fall,https://www.atkins.com/,North Dakota,Museum/gallery exhibitions officer
29,8fe66315-2b51-455c-b1a6-d7fabf84db3f,Erik,Greene,rebeccaharrison@example.org,537.502.6290,Robert Divide,https://www.soto.com/,Oregon,Chief Operating Officer
32,fc7938de-acf8-4d7f-8fcb-498d13aa84bc,Julie,Brown,annadavis@example.org,+1-838-578-0165x66984,Johnson View,https://hall.com/,South Carolina,Engineering geologist
34,6e3b07c7-c0f6-4854-bf09-3bfb9c5f2b75,Patricia,Long,shelby64@example.org,001-170-871-1027x201,Taylor Stravenue,https://www.harper-branch.info/,Texas,Theatre manager
35,d87f4ae1-3331-4e4c-a8b1-4e131be6716b,James,Solis,caitlinthomas@example.com,001-861-766-6504x7217,Velazquez Walk,https://www.cole.biz/,Maryland,Dietitian
36,5a8b67ad-cb37-416b-b5fc-c20b747d3ea2,Kevin,Scott,lisabarber@example.net,+1-233-902-7881,Gabriella Plaza,https://www.miller-ryan.com/,Kansas,Copy
46,4b4f9488-ac14-49e8-80c2-4ffd166138fd,Joseph,Galloway,deannamartinez@example.net,719.206.9548x8598,Elizabeth Landing,https://www.bryant-williams.net/,Florida,Sports development officer
48,58c21682-6f65-4bf5-afc5-b6ade9547dd9,Elizabeth,Hamilton,trevorallen@example.net,508.548.0928,Berry Mission,https://www.franklin.com/,Massachusetts,"Librarian, public"
51,42715bb7-eb32-482b-9324-2bede8a08e4e,Krystal,Santos,patricia29@example.com,432-337-7262x6396,Jennifer Ways,http://rivera-thornton.com/,Louisiana,"Development worker, community"
55,57de666d-e012-49ca-a929-9ebafac1a664,Felicia,Meyer,marthayoung@example.com,001-442-498-5131x1293,Gonzales Freeway,https://simmons.com/,Kansas,Community development worker
56,85c0f47d-2aaf-44d2-913a-eb6f28fa8ebf,Mary,Bernard,ymcbride@example.net,295-386-1652x7599,Anthony Villages,http://weber.com/,Vermont,Lobbyist
57,9f7622fe-70b6-4f29-906a-b3894509e87e,Curtis,James,tcordova@example.org,001-015-210-9952x7577,Robbins Neck,https://hunter.com/,Pennsylvania,"Conservation officer, historic buildings"
58,3fe330ed-95c1-47be-bdfb-65e9e28186bf,Nicholas,Anderson,lauravalentine@example.net,460.052.7978,Lambert Keys,http://www.thornton.org/,Ohio,Applications developer
60,689ab1f2-b204-4df9-9432-f85da2dee60b,Jessica,Adams,walshkristen@example.com,0695957770,Robert Trafficway,https://collier.com/,Illinois,"Designer, ceramics/pottery"
64,e786f27f-2bd0-45e2-9592-cc3021c52886,Elizabeth,Johnson,wooderic@example.org,(445)409-8411x732,Christopher Park,http://torres.com/,Nevada,Pharmacologist
70,ae34710c-b6bc-4588-b1ca-fc4fa0bd9724,Amanda,Garcia,chavezstephen@example.net,(640)115-3484x262,Blake Prairie,http://little.com/,Mississippi,Purchasing manager
71,aa24a92c-11cf-413a-9545-29fddf09a905,Kelly,Green,qacosta@example.net,(617)605-0540,Brown Gardens,https://www.rivas-allen.com/,Alaska,Pathologist
74,e51a709e-67c6-4520-a495-5d5c7eaffc39,Brian,Ross,destinywhite@example.net,8077185315,Lee Branch,https://wise.info/,South Carolina,Site engineer
77,f795baf7-f585-4edf-866f-98610635b178,Elizabeth,Mcmillan,uosborne@example.net,001-036-084-6305x5209,Rebecca Light,https://cantu.com/,Virginia,"Research officer, trade union"
78,b786fa0e-c95a-46b4-9779-8ba916ced4a4,Rodney,Ward,ddean@example.org,946.840.1503,Anthony Parkways,https://gaines-taylor.com/,West Virginia,"Presenter, broadcasting"
80,dbaf7f0f-1582-4fa0-a8b4-99270b1ccc29,Tiffany,Flowers,scottcox@example.com,682-433-1168x100,Wilson Plains,http://www.harris-anderson.com/,Maine,Photographer
81,9a1e5e95-d583-4991-a891-be067b2e3bff,Julie,Mills,kim01@example.com,703-861-6807x8972,Johnson Views,https://www.silva.com/,Oregon,Armed forces technical officer
82,8c866bbe-584e-44ae-bc3c-1b7567ea43a2,Amanda,Young,anthonyscott@example.com,001-147-617-0346x34276,Melissa Union,https://www.walton.net/,Texas,Marine scientist
84,599bfc26-404b-41e1-9236-91b39f5cac47,Dalton,Williams,pauldiaz@example.org,657-754-5027x42990,Mora Summit,https://carroll.com/,Utah,"Journalist, broadcasting"
85,b5acd8ab-03d2-4add-97fa-d71cdbfada0c,Stephen,Woodward,brittneypayne@example.com,7875616986,Walsh Road,https://www.williams.com/,Maryland,Chief Financial Officer
88,4fe842bf-3316-4789-b011-9a88e8017948,Russell,Brooks,matthew77@example.com,029-539-9605,Bentley Ridge,http://smith-mathews.biz/,Ohio,"Engineer, maintenance (IT)"
89,c6191bbd-1c35-463b-8028-67d71bb9f7ea,Evelyn,Stanley,rachelcohen@example.com,233-217-8207x64108,Jones Views,http://nichols.com/,Washington,Legal secretary
91,caafb794-4a82-4f41-a7a6-b467f894c609,Daniel,Mason,burtonian@example.org,311.489.0560x53609,Rachel Groves,http://long-meyer.com/,Texas,Operations geologist
96,e85220e4-7460-4e21-a830-6a753daccaf1,Maria,Butler,dorseypeter@example.com,001-767-480-1589x570,Joanna Ramp,https://davis.net/,New Mexico,Human resources officer
98,2fa419bf-4754-453a-89e8-e6be0b015483,Jason,Cook,vsanchez@example.com,001-174-323-2673x64856,Kristina Gardens,https://www.lopez-anderson.com/,Idaho,Publishing copy

In [ ]:
df1